'use server'
import { Puzzle } from "@/types";

const puzzles: Puzzle[] = [
  {
    puzzleName: "Enigma of Numbers",
    topics: ["Math", "Logic"],
    puzzleDescription: "Decode a sequence of numbers based on a mathematical pattern.",
    pointValue: 100,
    difficulty: 2,
    authors: ["Jane Doe", "John Smith"],
    solves: 50,
    linkToFiles: "https://example.com/puzzle1",
    hints: ["Consider Fibonacci sequences.", "Think about prime numbers."],
    teamSolved: false,
    userSolved: false,
  },
  {
    puzzleName: "Maze of Mirrors",
    topics: ["Geometry", "Spatial Reasoning"],
    puzzleDescription: "Find the shortest path in a reflective maze.",
    pointValue: 200,
    difficulty: 3,
    authors: ["Alice Wonderland"],
    solves: 30,
    linkToFiles: "https://example.com/puzzle2",
    hints: ["Symmetry is your friend.", "Trace paths from the end."],
    teamSolved: true,
    userSolved: false,
  },
  {
    puzzleName: "Cryptic Crossword",
    topics: ["Language", "Logic"],
    puzzleDescription: "Solve this challenging cryptic crossword.",
    pointValue: 150,
    difficulty: 2,
    authors: ["Clark Kent"],
    solves: 70,
    linkToFiles: "https://example.com/puzzle3",
    hints: ["Break words into smaller parts.", "Focus on double meanings."],
    teamSolved: true,
    userSolved: true,
  },
  {
    puzzleName: "Quantum Riddle",
    topics: ["Physics", "Math"],
    puzzleDescription: "Understand the paradox of Schrödinger's cat through clues.",
    pointValue: 300,
    difficulty: 3,
    authors: ["Stephen Hawking"],
    solves: 10,
    linkToFiles: "https://example.com/puzzle4",
    hints: ["Think about quantum states.", "Probabilities hold the key."],
    teamSolved: false,
    userSolved: false,
  },
  {
    puzzleName: "Lost in Translation",
    topics: ["Linguistics", "Culture"],
    puzzleDescription: "Translate a text written in a fictional language.",
    pointValue: 180,
    difficulty: 2,
    authors: ["Noam Chomsky"],
    solves: 40,
    linkToFiles: "https://example.com/puzzle5",
    hints: ["Look for grammatical patterns.", "Spot common word endings."],
    teamSolved: true,
    userSolved: false,
  },
  {
    puzzleName: "Chess Master’s Challenge",
    topics: ["Chess", "Strategy"],
    puzzleDescription: "Find the winning move in a complex chess game.",
    pointValue: 120,
    difficulty: 1,
    authors: ["Magnus Carlsen"],
    solves: 100,
    linkToFiles: "https://example.com/puzzle6",
    hints: ["Control the center.", "Think two moves ahead."],
    teamSolved: true,
    userSolved: true,
  },
  {
    puzzleName: "Code Breaker",
    topics: ["Cryptography"],
    puzzleDescription: "Decrypt the secret message using Caesar cipher.",
    pointValue: 90,
    difficulty: 1,
    authors: ["Alan Turing"],
    solves: 80,
    linkToFiles: "https://example.com/puzzle7",
    hints: ["Shift letters systematically.", "Frequency analysis helps."],
    teamSolved: true,
    userSolved: true,
  },
  {
    puzzleName: "Map the Stars",
    topics: ["Astronomy"],
    puzzleDescription: "Identify constellations based on a star map.",
    pointValue: 110,
    difficulty: 1,
    authors: ["Carl Sagan"],
    solves: 85,
    linkToFiles: "https://example.com/puzzle8",
    hints: ["Start with the brightest stars.", "Look for familiar patterns."],
    teamSolved: true,
    userSolved: false,
  },
  {
    puzzleName: "Tower of Hanoi Challenge",
    topics: ["Math", "Logic"],
    puzzleDescription: "Solve a complex Tower of Hanoi puzzle with 7 disks.",
    pointValue: 200,
    difficulty: 3,
    authors: ["Leonhard Euler"],
    solves: 25,
    linkToFiles: "https://example.com/puzzle9",
    hints: ["Follow recursive patterns.", "Move one disk at a time."],
    teamSolved: false,
    userSolved: false,
  },
  {
    puzzleName: "Periodic Puzzle",
    topics: ["Chemistry"],
    puzzleDescription: "Identify elements based on cryptic descriptions.",
    pointValue: 140,
    difficulty: 2,
    authors: ["Marie Curie"],
    solves: 60,
    linkToFiles: "https://example.com/puzzle10",
    hints: ["Focus on atomic numbers.", "Look for isotopes."],
    teamSolved: true,
    userSolved: true,
  },
  {
    puzzleName: "The Da Vinci Cipher",
    topics: ["History", "Cryptography"],
    puzzleDescription: "Decode a cipher found in Da Vinci’s sketches.",
    pointValue: 250,
    difficulty: 3,
    authors: ["Robert Langdon"],
    solves: 20,
    linkToFiles: "https://example.com/puzzle11",
    hints: ["Use substitution ciphers.", "Study Renaissance symbology."],
    teamSolved: false,
    userSolved: false,
  },
  {
    puzzleName: "Shakespeare’s Riddles",
    topics: ["Literature"],
    puzzleDescription: "Solve riddles hidden within Shakespearean texts.",
    pointValue: 120,
    difficulty: 1,
    authors: ["William Shakespeare"],
    solves: 90,
    linkToFiles: "https://example.com/puzzle12",
    hints: ["Look for metaphors.", "Focus on rhythm and structure."],
    teamSolved: true,
    userSolved: true,
  },
  {
    puzzleName: "Logic Circuit Mystery",
    topics: ["Electronics", "Logic"],
    puzzleDescription: "Analyze a circuit to find its output.",
    pointValue: 200,
    difficulty: 2,
    authors: ["Nikola Tesla"],
    solves: 55,
    linkToFiles: "https://example.com/puzzle13",
    hints: ["Use truth tables.", "Break the circuit into smaller parts."],
    teamSolved: true,
    userSolved: false,
  },
  {
    puzzleName: "Riddle of the Sphinx",
    topics: ["Mythology"],
    puzzleDescription: "Answer the age-old riddle of the Sphinx.",
    pointValue: 100,
    difficulty: 0,
    authors: ["Homer"],
    solves: 200,
    linkToFiles: "https://example.com/puzzle14",
    hints: ["Consider basic human traits.", "Think about the passage of time."],
    teamSolved: true,
    userSolved: true,
  },
  {
    puzzleName: "Sudoku Mastery",
    topics: ["Logic"],
    puzzleDescription: "Solve a challenging 16x16 Sudoku puzzle.",
    pointValue: 180,
    difficulty: 3,
    authors: ["Sudoku Guru"],
    solves: 45,
    linkToFiles: "https://example.com/puzzle15",
    hints: ["Use elimination strategies.", "Fill in obvious cells first."],
    teamSolved: false,
    userSolved: false,
  },
  {
    puzzleName: "Escape the Room",
    topics: ["Logic", "Mystery"],
    puzzleDescription: "Use clues to escape a locked virtual room.",
    pointValue: 220,
    difficulty: 3,
    authors: ["Escape Artist"],
    solves: 15,
    linkToFiles: "https://example.com/puzzle16",
    hints: ["Examine every detail.", "Combine items creatively."],
    teamSolved: false,
    userSolved: false,
  },
  {
    puzzleName: "Morse Code Conundrum",
    topics: ["Cryptography"],
    puzzleDescription: "Translate a series of Morse code signals.",
    pointValue: 80,
    difficulty: 1,
    authors: ["Samuel Morse"],
    solves: 120,
    linkToFiles: "https://example.com/puzzle17",
    hints: ["Use a Morse code chart.", "Focus on timing of signals."],
    teamSolved: true,
    userSolved: true,
  },
  {
    puzzleName: "Island Survivor",
    topics: ["Strategy", "Logic"],
    puzzleDescription: "Plan your escape from a deserted island.",
    pointValue: 170,
    difficulty: 2,
    authors: ["Robinson Crusoe"],
    solves: 70,
    linkToFiles: "https://example.com/puzzle18",
    hints: ["Prioritize essentials.", "Map out resources carefully."],
    teamSolved: true,
    userSolved: false,
  },
  {
    puzzleName: "DNA Decoding",
    topics: ["Biology", "Genetics"],
    puzzleDescription: "Identify genetic markers in a DNA sequence.",
    pointValue: 200,
    difficulty: 2,
    authors: ["Gregor Mendel"],
    solves: 50,
    linkToFiles: "https://example.com/puzzle19",
    hints: ["Focus on codons.", "Search for repeating sequences."],
    teamSolved: true,
    userSolved: false,
  },
  {
    puzzleName: "Piano Puzzle",
    topics: ["Music"],
    puzzleDescription: "Identify a tune based on musical notes and patterns.",
    pointValue: 100,
    difficulty: 1,
    authors: ["Ludwig van Beethoven"],
    solves: 95,
    linkToFiles: "https://example.com/puzzle20",
    hints: ["Think about scales.", "Focus on intervals."],
    teamSolved: true,
    userSolved: true,
  },
];


export async function getPuzzles(
  page: number = 0,
  limit: number = 9
): Promise<{ puzzles: Puzzle[]; total: number }> {
  // Calculate the start and end indices for the current page
  const start = page * limit;
  const end = start + limit;

  // Return the sliced puzzles and the total number of puzzles
  return {
    puzzles: puzzles.slice(start, end),
    total: puzzles.length, // Total number of puzzles available
  };
}