name: Build and Lint

# Trigger the workflow on push and pull requests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js version >= 18.17.0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the build command for Next.js
      - name: Build project
        run: npm run build

  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js version >= 18.17.0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run linting
      - name: Run linter
        run: npm run lint
